[package]
name = "binman"
version = "0.2.2"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
dirs = "3.0.1"
http = "0.2.2"
rood = "0.2.0"
regex = "1.4.2"
reqwest = { version = "0.10", features = ["json"]}
semver = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
sha2 = "0.9.2"
shellexpand = "2.1.0"
tempfile = "3.1.0"
tokio = "1.0.1"
walkdir = "2"
