[package]
name = "binman"
version = "0.3.0"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "binlib"
path = "src/binlib/lib.rs"

[[bin]]
name = "binman"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = "3.0.0-beta.2"
dirs = "3.0.1"
http = "0.2.3"
rood = "0.2.0"
regex = "1.4.3"
reqwest = { version = "0.11", features = ["json"]}
semver = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.61"
sha2 = "0.9.2"
shellexpand = "2.1.0"
tempfile = "3.2.0"
tokio = { version = "1.0", features = ["full"] }
walkdir = "2"
