[package]
name = "binman"
version = "0.2.2"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
dirs = "2.0.2"
http = "0.2.0"
rood = "0.1.4"
regex = "1.3.4"
reqwest = { version = "0.10", features = ["json"]}
semver = { version = "0.9.0", features = ["serde"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.46"
sha2 = "0.8.1"
shellexpand = "1.1.1"
tempfile = "3.1.0"
tokio = "0.2.11"
walkdir = "2"
