name: Validate & Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Bootstrap Landlord
        run: |
          sudo wget https://github.com/purposed/landlord/releases/v0.1.5/download/landlord-linux-amd64 -O /usr/local/bin/landlord
          sudo chmod +x /usr/local/bin/landlord
      - name: Landlord Release
        run: |
          landlord validate
          landlord release
      - name: Release
        uses: docker://softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/linux-amd64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
