name: Validate & Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Mount build cache
        uses: actions/cache@v1
        with:
          path: "target"
          key: binman-release-cache
      - name: Build/Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename
        run: |
          mv target/release/binman binman-linux-amd64
      - name: Release
        uses: docker://softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: binman-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
